#
###################################
# Site wide configuration
####################################
#
title: "Timmy Nguyen"
email: message.timmynguyen@gmail.com
description: portfolio of nguyen17
url: https://nguyen17.github.io/Portfolio/
keywords: ["nguyen17", "timmy nguyen"]

#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Timmy Nguyen"
  avatar: ""
  job: "Software Engineer & Ruby Developer | UI & UX"
  bio: "UNLV Undergraduate Student - BA of Computer Science and Biology minor. Passionate for web technologies and user interaction."
  email: message.timmynguyen@gmail.com
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:

  github: nguyen17 ##username
  codepen: nineclove ##username
